In [15]:
import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import os

/Users/cristianespinosa/opt/anaconda3/envs/tensor/lib/python3.10/site-packages/google/api_core/_python_version_support.py:266: FutureWarning: You are using a Python version (3.10.19) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

In [21]:
GEMINI_API_KEY = "AIzaSyBNkvSVjQAaPgcAA9F4ysAzO8G_PLwZQYU"
url = "https://aoe3homecity.com/en/statistics/leaderboard/"
game_modes = ["1vs1", "teamSupremacy", "treaty"]

In [22]:
response = requests.get(url+game_modes[0])

html = response.text

print(html[:500])

<!DOCTYPE html><html lang="en" dir="ltr"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="stylesheet" href="/_next/static/css/10f5cd8238286272.css" data-precedence="next"/><link rel="stylesheet" href="/_next/static/css/59e54c2c3ac9c77d.css" data-precedence="next"/><link rel="preload" as="script" fetchPriority="low" href="/_next/static/chunks/webpack-9d3e279d5d246217.js"/><script src="/_next/static/chunks/4bd1b696-bad92808725a934a.js" as

In [23]:
# clean html
soup = BeautifulSoup(html, "html.parser")

# Remove scripts/styles
for tag in soup(["script", "style"]):
    tag.decompose()

clean_text = soup.get_text(separator="\n")

print(clean_text)

Statistics
Ranked
Strategies
Civilizations
Units
Maps
Age of Empires III: Definitive Edition © Microsoft Corporation

This site was created under Microsoft's "
Game Content Usage Rules
" using assets from

Age of Empires III: Definitive Edition
, and it is not endorsed by or affiliated with Microsoft.
Created by Dori

 eBaeza
 Dori Server
 Discord ID
 dori_mx
 @dori7668
 contact me
Leaderboard - Supremacy (1v1) | AOE 3 Home City
Mode
Supremacy (1v1)
Thanks to @hellpunch for the data services. You can check all original data from

aoe3explorer.com

In [18]:
genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

In [19]:
prompt = f"""
Extract Age of Empires 3 player statistics from this webpage text.

Return ONLY valid JSON.

Fields:
- player_name
- elo_1v1
- elo_team
- top_1v1_civs
- top_team_civs
- total_games

Webpage text:
{clean_text}
"""

response = model.generate_content(prompt)

print(response.text)

```json
[]
```

In [24]:
import pandas as pd
df = pd.read_csv('./Leaderboard - Supremacy (1v1) _ AOE 3 Home City.csv')
df

          #    ELO           Player   Clan Streak Percent  Games  Last game
0         1  2,513          JulianK    τKc     14  74.64%  3,316   5/9/2026
1         2  2,436         Keturboy  Tur4n      1  68.87%    575   5/7/2026
2         3  2,352         OnlyBaus     '-      2  64.29%  1,092   5/1/2026
3         4  2,287             Toji     '-      1  66.44%    894  5/10/2026
4         5  2,285          Optimus     '-     31  69.89%  2,305   5/3/2026
...     ...    ...              ...    ...    ...     ...    ...        ...
4520  4,521    208          Facue97  Espir    '-4  31.17%    308   5/6/2026
4521  4,522    164    andreag240806     '-   '-12  11.48%    183  4/17/2026
4522  4,523    162              杨天佑    小星星   '-14  35.67%    328  5/10/2026
4523  4,524    125        gokhan105     '-   '-20  19.28%    415   5/3/2026
4524  4,525    118  FlipFall7167464     '-   '-17  16.04%    667   5/6/2026

[4525 rows x 8 columns]

There is a website called https://aoe3homecity.com/en/statistics/leaderboard/teamSupremacy and https://aoe3homecity.com/en/statistics/leaderboard/1vs1, under which inside dividers, ```data-id=xxxxxxxx``` is what shows the player's id. Grab that number and the rest is simple:
- aoe3homecity.com/players/data-id-number/1vs1
- aoe3homecity.com/players/data-id-number/teamSupremacy

I would like to ask you to grab the player ids and grab their statistics for both game modes: 1vs1 and team supremacy, and present them in a neat embedded way to showcase in discord.

In [26]:
df[df['Clan'] == "R3VOS"]

          #    ELO           Player   Clan Streak Percent  Games  Last game
580     581  1,476          Joselow  R3VOS      2  51.49%    771  5/10/2026
709     710  1,421           azail3  R3VOS    '-1  54.49%    334  4/29/2026
778     779  1,391        DIES IRAE  R3VOS      1  50.92%  1,408   5/9/2026
1367  1,368  1,214  jhonatan1252653  R3VOS      2  58.62%     58   5/9/2026
1705  1,706  1,146   Revolucionario  R3VOS      2  50.51%    778   5/8/2026
2158  2,159  1,071        Juanva12x  R3VOS      2  60.49%     81   5/3/2026
2367  2,368  1,037    El Niño Tinto  R3VOS    '-2  50.49%    719  4/20/2026
3622  3,623    818         MeRaKi69  R3VOS    '-1  41.46%     41  4/30/2026
3968  3,969    713   SERGI_LA_LINEA  R3VOS    '-3  46.72%    122   5/9/2026
4005  4,006    700      AKoberstein  R3VOS      1  32.35%     34  5/10/2026